name: CI
on:
  push:

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: CI
        run: |
          bun install
          bun scripts/prepare.ts
          bun test --rerun-each 5
