name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: CI
        run: |
          bun install
          bun test --timeout 10000 --rerun-each 10
      - name: Publish package
        run: npx jsr publish
